name: Continuous Integration
on:
    push:
        branches: 
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        
        steps:
            - name: Check out Code
              uses: actions/checkout@v2  

            - name: Set Up JDK 17
              uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'temurin' 

            - name: Validate Gradle wrapper
              uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
              
            - name: Build with Gradle
              run: ./gradlew build
              
            - name: Run Tests with Jacoco coverage
              run: ./gradlew test jacocoTestReport

            - name: Check code coverage
              run: |
                total_coverage=$(grep -Po "\d+(?=%)" build/reports/jacoco/test/html/index.html | head -n 1)
                if ["$total_coverage" -eq "100"]; then
                    echo "Unit tests passed with 100% code coverage"
                else
                    echo "Code Coverage is not 100%. Please add more tests."
                    exit 1
                fi  